<?xml version="1.0"?>
<robot name="new_car"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!--定义变量及常数-->
    <xacro:property name="PI" value="3.1415926"/>

    <xacro:property name="car_width" value="0.6"/>
    <xacro:property name="car_length" value="1.2"/>
    <xacro:property name="car_height" value="0.3"/>

    <xacro:property name="wheel_length" value="0.13"/>
    <xacro:property name="wheel_radius" value="0.28"/>

    <xacro:property name="wheel_origin_xyz" value="0.0 0.0 0.0"/>
    <xacro:property name="wheel_origin_rpy" value="0.0 ${PI/2} 0.0"/>

    <!--定义材质-->
    <material name="yellow">
        <color rgba="0.996 0.416 0.0 1.0"/>
    </material>

    <material name="black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>


    <!--宏定义-->

    <xacro:macro name="default_origin" params="xyz rpyaw">
        <origin xyz="${xyz}" rpy="${rpyaw}"/>
    </xacro:macro>
    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0" />
        </inertial>
    </xacro:macro>
    <xacro:macro name="cylinder_geometry" params="length radius">
        <geometry>
            <cylinder length="${length}" radius="${radius}"/>
        </geometry>
    </xacro:macro>
    <xacro:macro name="box_geometry" params="width length height">
        <geometry>
            <box size="${width} ${length} ${height}"/>
        </geometry>
    </xacro:macro>



<!--车身link-->
    <link name="car_link">
        <visual>
            <xacro:box_geometry width="${car_width}" length="${car_length}" height="${car_height}"/>
            <material name="yellow"/>
        </visual>
        <collision>
            <xacro:box_geometry width="${car_width}" length="${car_length}" height="${car_height}"/>
        </collision>
        <xacro:default_inertial mass="3.0"/>

    </link>


    <gazebo reference="car_link">
        <material>Gazebo/SkyBlue</material>
        <mu1>10000</mu1>
        <mu2>10000</mu2>
    </gazebo>


    <xacro:macro name="wheel_car_joint" params="wheel_name front_back left_right">
        <link name="${wheel_name}">
            <visual>
                <xacro:cylinder_geometry length="${wheel_length}" radius="${wheel_radius}"/>
                <xacro:default_origin xyz="${wheel_origin_xyz}" rpyaw="${wheel_origin_rpy}" />
                <material name="black"/>
            </visual>
            <collision>
                <xacro:cylinder_geometry length="${wheel_length}" radius="${wheel_radius}"/>
                <xacro:default_origin xyz="${wheel_origin_xyz}" rpyaw="${wheel_origin_rpy}" />
            </collision>
            <xacro:default_inertial mass="1.0"/>
        </link>

        <joint name="car_base_${wheel_name}" type="continuous">
            <origin xyz="${left_right*(wheel_length+car_width)/2.0} ${front_back*car_length*0.6/2.0} 0.0" rpy="0.0 0.0 0.0"/>
            <!--利用left_right和front_back正负决定位置-->
            <parent link="car_link"/>
            <child link="${wheel_name}"/>
            <axis xyz="1.0 0.0 0.0"/>
        </joint>

        <gazebo reference="${wheel_name}">
            <material>Gazebo/Black</material>
            <mu1>100000</mu1>            <!--静摩擦-->
            <mu2>100000</mu2>            <!--动摩擦-->
        </gazebo>
<!--传动-->
        <transmission name="${wheel_name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="car_base_${wheel_name}">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}_motor">
                <mechanicalReducction>1</mechanicalReducction><!--传动比定为1-->
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:wheel_car_joint wheel_name="front_right_wheel" front_back="1.0" left_right="1.0"/>
    <xacro:wheel_car_joint wheel_name="front_left_wheel" front_back="1.0" left_right="-1.0"/>
    <xacro:wheel_car_joint wheel_name="back_right_wheel" front_back="-1.0" left_right="1.0"/>
    <xacro:wheel_car_joint wheel_name="back_left_wheel" front_back="-1.0" left_right="-1.0"/>

    <link name="base_link"/>
    <joint name="base_link_car" type="fixed">
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="car_link"/>
    </joint>
<gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
    </plugin>
</gazebo>
</robot>
