<robot name="mycar"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:include filename="inertial.xacro" />
    <xacro:include filename="wheel.xacro" />
    <xacro:property name="base_length" value="0.2" />
    <xacro:property name="base_width" value="0.18" />
    <xacro:property name="base_height" value="0.05" />
    <xacro:property name="base_mass" value="2" />
    <xacro:property name="lidi" value="0.015" />
    <xacro:macro name="chassis" params="foobar">
        <xacro:property name="footprint_radius" value="0.001" />
        <link name="base_footprint">
            <visual>
                <geometry>
                    <sphere radius="${footprint_radius}" />
                </geometry>
            </visual>
        </link>
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="yellow">
                    <color rgba="0.5 0.3 0.0 0.5" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:box_inertial_matrix m="${base_mass}" l="${base_length}" w="${base_width}"
                h="${base_height}" />
        </link>
        <gazebo reference="base_link">
            <material>
                Gazebo/Yellow
            </material>
        </gazebo>
        <joint name="base_link2base_footprint" type="fixed">
            <parent link="base_footprint" />
            <child link="base_link" />
            <origin xyz="0 0 ${base_height/2+lidi}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
        <xacro:property name="wheel_offset_z" value="${-(base_height/2+lidi-wheel_radius)}" />
        <xacro:wheel_func prefix="left_front" connected_to="base_link"
            wheel_x_offset="${base_length/3}" wheel_y_offset="${base_width/2}"
            wheel_z_offset="${wheel_offset_z}" />
        <xacro:wheel_func prefix="right_front" connected_to="base_link"
            wheel_x_offset="${base_length/3}" wheel_y_offset="${-base_width/2}"
            wheel_z_offset="${wheel_offset_z}" />
        <xacro:wheel_func prefix="left_back" connected_to="base_link"
            wheel_x_offset="${-base_length/3}" wheel_y_offset="${base_width/2}"
            wheel_z_offset="${wheel_offset_z}" />
        <xacro:wheel_func prefix="right_back" connected_to="base_link"
            wheel_x_offset="${-base_length/3}" wheel_y_offset="${-base_width/2}"
            wheel_z_offset="${wheel_offset_z}" />
        <xacro:wheel_transmission prefix="left_front" mechanical_reduction="1" />
        <xacro:wheel_transmission prefix="right_front" mechanical_reduction="-1" />
        <xacro:wheel_transmission prefix="left_back" mechanical_reduction="1" />
        <xacro:wheel_transmission prefix="right_back" mechanical_reduction="-1" />
    </xacro:macro>
</robot>
